// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvulziVkCX5WByHUJi4-I5jVITKakhjM',
    appId: '1:865247480459:web:2da81803d9b96f1af9628e',
    messagingSenderId: '865247480459',
    projectId: 'chatting-app-49f6f',
    authDomain: 'chatting-app-49f6f.firebaseapp.com',
    storageBucket: 'chatting-app-49f6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5rOQI2myeHaLL-CCfNhBRXKm0hv_AmU',
    appId: '1:865247480459:android:69b6b1336efbb39cf9628e',
    messagingSenderId: '865247480459',
    projectId: 'chatting-app-49f6f',
    storageBucket: 'chatting-app-49f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHG3kXw2tixMQywMwC1zLGA05yC0ptPdw',
    appId: '1:865247480459:ios:4ce1c3352e171d23f9628e',
    messagingSenderId: '865247480459',
    projectId: 'chatting-app-49f6f',
    storageBucket: 'chatting-app-49f6f.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHG3kXw2tixMQywMwC1zLGA05yC0ptPdw',
    appId: '1:865247480459:ios:4ce1c3352e171d23f9628e',
    messagingSenderId: '865247480459',
    projectId: 'chatting-app-49f6f',
    storageBucket: 'chatting-app-49f6f.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYvulziVkCX5WByHUJi4-I5jVITKakhjM',
    appId: '1:865247480459:web:9251886b6ee7bb5ef9628e',
    messagingSenderId: '865247480459',
    projectId: 'chatting-app-49f6f',
    authDomain: 'chatting-app-49f6f.firebaseapp.com',
    storageBucket: 'chatting-app-49f6f.appspot.com',
  );
}
